sonar.projectKey=siem
sonar.projectName=SIEM

sonar.sources=backend/app

sonar.host.url=http://localhost:9000

sonar.python.version=3.13

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/node_modules/**
